# Generated by Django 5.2.13 on 2026-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_bu_scope_and_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-last_updated', '-id']},
        ),
        migrations.AlterModelOptions(
            name='documentfolder',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
