# Generated by Django 5.2.13 on 2026-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mentioned in Post'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('leave_notify', 'Leave Notify'), ('post_comment', 'Comment on Post'), ('post_reaction', 'Reaction on Post'), ('poll_vote', 'Poll Vote'), ('attendance_alert', 'Attendance Alert'), ('system', 'System Announcement')], max_length=30),
        ),
    ]
