# Generated by Django 5.2.13 on 2026-04-22 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_zipcode_unique_together'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceday',
            old_name='is_week_off',
            new_name='is_locked',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='effective_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='gross_hours',
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='total_gross_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='total_work_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='break_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_in_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_out_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_within_geofence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='work_mode',
            field=models.CharField(choices=[('office', 'Office'), ('wfh', 'Work From Home'), ('remote', 'Remote')], default='office', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendanceday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='attendanceday',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('week_off', 'Week Off'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='attendance_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendanceday'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='accounts.employee'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_57ae6e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['employee', 'check_in'], name='attendance__employe_d1924d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['attendance_day'], name='attendance__attenda_12e915_idx'),
        ),
    ]
