# Generated by Django 5.2.13 on 2026-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_unique_pending_regularization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceday',
            new_name='attendance__employe_ca6ef5_idx',
            old_name='attendance__employe_9c4e2b_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancepolicy',
            new_name='attendance__busines_6af67d_idx',
            old_name='attendance__busines_8a0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceregularization',
            new_name='attendance__employe_7d7734_idx',
            old_name='attendance__employe_7b2d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeshiftassignment',
            new_name='attendance__employe_51ac71_idx',
            old_name='attendance__employe_1a3f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='overtimerequest',
            new_name='attendance__employe_00b13d_idx',
            old_name='attendance__employe_ot_idx',
        ),
        migrations.RenameIndex(
            model_name='shift',
            new_name='attendance__busines_cdbb65_idx',
            old_name='attendance__busines_2c8f1a_idx',
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='block_punch_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='block_punch_on_week_off',
            field=models.BooleanField(default=True),
        ),
    ]
