# Generated by Django 5.2.13 on 2026-04-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_country_state_city_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('name_on_document', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='identity_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='accounts.employee')),
            ],
            options={
                'unique_together': {('employee', 'identity_type')},
            },
        ),
    ]
