# Generated by Django 5.2.13 on 2026-04-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_identityinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('district', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipcodes', to='accounts.city')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='accounts_zi_code_875e54_idx')],
                'unique_together': {('code', 'city')},
            },
        ),
    ]
