# Generated by Django 5.2.13 on 2026-04-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_zipcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zipcode',
            unique_together={('code', 'city', 'district')},
        ),
    ]
