# Generated by Django 5.2.13 on 2026-04-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_zipcode_unique_together'),
        ('leave', '0001_initial'),
        ('organization', '0002_weeklyoffpolicy_businessunit_weekly_off_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='requested_by',
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type')},
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='annual_quota',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_allocated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('action_taken_on', models.DateTimeField(blank=True, null=True)),
                ('is_consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='accounts.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='leave.leavetype')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_leaves', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField()),
                ('max_per_month', models.IntegerField(blank=True, null=True)),
                ('carry_forward', models.BooleanField(default=False)),
                ('requires_document', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='leave.leavetype')),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveDay',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='available',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='consumed',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='year',
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='leave_leave_employe_05b852_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_leave_start_d_5dff54_idx'),
        ),
    ]
