# Generated by Django 5.2.13 on 2026-04-27 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_zipcode_unique_together'),
        ('leave', '0002_remove_leaverequest_action_by_and_more'),
        ('organization', '0002_weeklyoffpolicy_businessunit_weekly_off_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavepolicy',
            old_name='carry_forward',
            new_name='carry_forward_allowed',
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leave',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='max_per_month',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_days_per_month',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_days_per_year',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='requires_document',
        ),
        migrations.AddField(
            model_name='leave',
            name='duration_type',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half'), ('multi_day', 'Multiple Days')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='total_days',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='adjustments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Positive or negative manual adjustments', max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_forward',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='business_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.businessunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='document_required_after_days',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Require document only if leave exceeds this many days', max_digits=4),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='max_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='max_days_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='total_days_allocated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='action_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves_history', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_leaves_history', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_allocated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
