# Generated by Django 5.2.13 on 2026-04-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_rename_carry_forward_leavepolicy_carry_forward_allowed_and_more'),
        ('organization', '0002_weeklyoffpolicy_businessunit_weekly_off_policy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavepolicy',
            unique_together={('business_unit', 'leave_type')},
        ),
    ]
