# Generated by Django 5.2.13 on 2026-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leavepolicy_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='duration_type',
        ),
        migrations.AddField(
            model_name='leave',
            name='end_day_session',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_day_session',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20),
        ),
    ]
