# Generated by Django 5.2.13 on 2026-04-28 10:45

import django.db.models.deletion
import django.utils.timezone
import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_weeklyoffpolicy_businessunit_weekly_off_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='weekly_off_policy',
        ),
        migrations.RemoveField(
            model_name='weeklyoffpolicy',
            name='off_days',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weeklyoffpolicy',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_off_policies', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='weeklyoffpolicy',
            name='policy_rules',
            field=models.JSONField(default=dict, help_text="Format: {'6': 'all', '5': [1, 3]} where 0=Mon, 6=Sun.", validators=[organization.models.validate_complex_off_days]),
        ),
    ]
