# Generated by Django 5.2.13 on 2026-05-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_businessunit_weekly_off_policy_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyoffpolicy',
            unique_together={('business_unit', 'name')},
        ),
    ]
