# Generated by Django 5.2.13 on 2026-05-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_zipcode_unique_together'),
        ('organization', '0004_alter_weeklyoffpolicy_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('standard', 'Standard Post'), ('announcement', 'Announcement'), ('poll', 'Poll')], default='standard', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_posts', to='accounts.employee')),
                ('target_business_unit', models.ForeignKey(blank=True, help_text='Leave blank for company-wide global posts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_posts', to='organization.businessunit')),
                ('target_department', models.ForeignKey(blank=True, help_text='Leave blank to show to the entire Business Unit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_posts', to='organization.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to disable this holiday without permanently deleting the record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_leave_days', to='organization.businessunit')),
            ],
            options={
                'verbose_name': 'Leave Day (Holiday)',
                'verbose_name_plural': 'Leave Days (Holidays)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('feed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='organization.feedpost')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('feed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_votes', to='organization.feedpost')),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='organization.polloption')),
            ],
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['target_business_unit', 'target_department', 'is_active'], name='organizatio_target__4ccc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='leavedays',
            index=models.Index(fields=['date', 'business_unit', 'is_active'], name='organizatio_date_2d4aca_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavedays',
            constraint=models.UniqueConstraint(fields=('date', 'business_unit'), name='unique_holiday_per_business_unit'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('feed_post', 'employee'), name='unique_vote_per_employee_per_poll'),
        ),
    ]
