# Generated by Django 5.2.13 on 2026-05-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_feedpost_leavedays_polloption_pollvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feed_posts/images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organization.feedpost')),
            ],
        ),
    ]
