# Generated by Django 5.2.13 on 2026-05-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_feedpost_comments_count_feedpost_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpostlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('haha', 'Haha'), ('heart', 'Heart'), ('clap', 'Clap'), ('curious', 'Curious')], default='like', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedpostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='organization.feedpost'),
        ),
    ]
